/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'LogGeneratedUsernames': EventHandler<{ requestId: string; success: boolean; theme?: string; keywords?: Array<string>; usernames: Array<string>; error?: string }, never>
    'RequestUsernameGeneration': ApiRouteHandler<{ theme: string; keywords?: Array<string>; count: number }, unknown, { topic: 'username.requested'; data: never }>
    'LogGreeting': EventHandler<{ requestId: string; greeting: string; processedBy: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
    'GenerateUsernamesWithAI': EventHandler<never, { topic: 'username.generated'; data: { requestId: string; success: boolean; theme?: string; keywords?: Array<string>; usernames: Array<string>; error?: string } }>
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, { topic: 'greeting-processed'; data: { requestId: string; greeting: string; processedBy: string } }>
  }
    
}